### ISSUE TITLE
How do you specify the Mode?

### ISSUE THREAD

**Issue by CouponPages** [VFPX/ClassBrowserX#1]
I've been looking for a tool that can convert SCX / VCX into working code for decades, so I was excited to hear about ClassBrowserX, but the code still doesn't run.

I see something about "Modes" in the readme file, but I can't find anything that says how to change it from the default mode 0, which doesn't support controls in containers, to 2, 3, 4, or 5, which do.

Can somebody add this to the readme?  I'm sure others may be looking for it too. 

Thanks!

**Comment by DougHennig** [comment]
I am not the author, but here's what I did:

- Searched for the text "Old MS way" in BrowserX.prg since README indicates that was taken from the PRG. That's found in the brwExportClass function, which makes sense,

- Looked at Arto's comments. It appears a variable named lnAppType is related to the new code.

- Looked at how lnAppType is assigned a value and found this:

```
* nShiftAltCtrl  Modifier key  
* 1              SHIFT
* 2              CTRL
* 4              ALT

* m.lnAppType = IIF(toBrowser.nShift==2,1,IIF(toBrowser.nShift==4,2,0))

* m.lnAppType = IIF(INLIST(toBrowser.nShift,2,3,4,5) AND toBrowser.lSCXMode,toBrowser.nShift,0)
m.lnAppType = IIF(INLIST(toBrowser.nShift,2,3,4,5),toBrowser.nShift,0)
```

So, it looks like you hold down a combination of the Shift, Ctrl, and Alt keys when you do the export to get the mode you want (I haven't tried it myself, just looked at the code).

Doug

**Comment by CouponPages** [comment]
Thanks Doug!

It seems pretty strange that the default behavior for this tool is to do exactly what the original Microsoft version does unless you use a strange combination of ShiftAltCtrl and a number, but I'll give it a try.

For what it's worth, it would be a good idea to hard code it the other way around, so it actually works by default... then use the ShiftAltCtrl keys to make it work like the Microsoft version (which never could generate workable code).

If it works with the hotkeys, I'll modify mine by hard-coding the mode.

Thanks again!

Joe

**Comment by CouponPages** [comment]
For the record....

I just tried it by holding down the Alt-Key when I clicked the View Class Code button... and Viola!

Here's the new header, showing that it did, in fact, change the mode... THANKS AGAIN DOUG!
`
***************************************************
* Class Browser modifications by Arto Toikka 2005 *
* =============================================== *
*                                                 *
* Mode 4                                          *
* View Code generated: 05/29/18 11:20:07 AM       *
***************************************************
`

**Comment by DougHennig** [comment]
Thanks for confirming. I updated the readme.
